server:
  port: 9001
spring:
  application:
    # 指定服务名
    name: user-server
eureka:
  client:
    serviceUrl:
      #  配置eureka-client
      defaultZone: http://localhost:9000/eureka/
  instance:
      # 配置IP
    prefer-ip-address: true
# person 配置类
person:
  name: polarbear
  age: 25
  number: 13667147095
  gender: 1